# Generated by Django 3.2.6 on 2025-04-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=100)),
                ('certification_id', models.CharField(max_length=100)),
                ('certification_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('course_type', models.CharField(max_length=100)),
                ('course_duration', models.CharField(max_length=100)),
                ('grading_system', models.CharField(max_length=100)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('startdate', models.DateField(max_length=100)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('project_details', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='experince',
            old_name='skils_used',
            new_name='skills_used',
        ),
    ]
